#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/meizu/m1822

PRODUCT_COPY_FILES += \
    vendor/meizu/m1822/proprietary/vendor/etc/acdbdata/common/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/common/Bluetooth_cal.acdb \
    vendor/meizu/m1822/proprietary/vendor/etc/acdbdata/common/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/common/General_cal.acdb \
    vendor/meizu/m1822/proprietary/vendor/etc/acdbdata/common/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/common/Global_cal.acdb \
    vendor/meizu/m1822/proprietary/vendor/etc/acdbdata/common/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/common/Handset_cal.acdb \
    vendor/meizu/m1822/proprietary/vendor/etc/acdbdata/common/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/common/Hdmi_cal.acdb \
    vendor/meizu/m1822/proprietary/vendor/etc/acdbdata/common/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/common/Headset_cal.acdb \
    vendor/meizu/m1822/proprietary/vendor/etc/acdbdata/common/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/common/Speaker_cal.acdb \
    vendor/meizu/m1822/proprietary/vendor/etc/acdbdata/na/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/na/Bluetooth_cal.acdb \
    vendor/meizu/m1822/proprietary/vendor/etc/acdbdata/na/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/na/General_cal.acdb \
    vendor/meizu/m1822/proprietary/vendor/etc/acdbdata/na/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/na/Global_cal.acdb \
    vendor/meizu/m1822/proprietary/vendor/etc/acdbdata/na/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/na/Handset_cal.acdb \
    vendor/meizu/m1822/proprietary/vendor/etc/acdbdata/na/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/na/Hdmi_cal.acdb \
    vendor/meizu/m1822/proprietary/vendor/etc/acdbdata/na/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/na/Headset_cal.acdb \
    vendor/meizu/m1822/proprietary/vendor/etc/acdbdata/na/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/na/Speaker_cal.acdb \
    vendor/meizu/m1822/proprietary/vendor/etc/init/android.hardware.biometrics.fingerprint@2.1-service-m1822.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.biometrics.fingerprint@2.1-service-m1822.rc \
    vendor/meizu/m1822/proprietary/vendor/etc/qdcm_calib_data_mipi_mot_vid_csot_720p_622.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_mipi_mot_vid_csot_720p_622.xml \
    vendor/meizu/m1822/proprietary/vendor/etc/qdcm_calib_data_mipi_mot_vid_ofilm_720p_622.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_mipi_mot_vid_ofilm_720p_622.xml \
    vendor/meizu/m1822/proprietary/vendor/etc/qdcm_calib_data_mipi_mot_vid_tianma_720p_622.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_mipi_mot_vid_tianma_720p_622.xml \
    vendor/meizu/m1822/proprietary/vendor/firmware/AbovCapSense.BIN:$(TARGET_COPY_OUT_VENDOR)/firmware/AbovCapSense.BIN \
    vendor/meizu/m1822/proprietary/vendor/firmware/FT8006U_Pramboot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/FT8006U_Pramboot.bin \
    vendor/meizu/m1822/proprietary/vendor/firmware/cpp_firmware_v1_10_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_10_0.fw \
    vendor/meizu/m1822/proprietary/vendor/firmware/cpp_firmware_v1_12_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_12_0.fw \
    vendor/meizu/m1822/proprietary/vendor/firmware/cpp_firmware_v1_1_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_1.fw \
    vendor/meizu/m1822/proprietary/vendor/firmware/cpp_firmware_v1_1_6.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_6.fw \
    vendor/meizu/m1822/proprietary/vendor/firmware/cpp_firmware_v1_2_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_2_0.fw \
    vendor/meizu/m1822/proprietary/vendor/firmware/cpp_firmware_v1_4_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_4_0.fw \
    vendor/meizu/m1822/proprietary/vendor/firmware/cpp_firmware_v1_5_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_0.fw \
    vendor/meizu/m1822/proprietary/vendor/firmware/cpp_firmware_v1_5_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_1.fw \
    vendor/meizu/m1822/proprietary/vendor/firmware/cpp_firmware_v1_5_2.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_2.fw \
    vendor/meizu/m1822/proprietary/vendor/firmware/cpp_firmware_v1_6_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_6_0.fw \
    vendor/meizu/m1822/proprietary/vendor/firmware/cpp_firmware_v1_8_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_8_0.fw \
    vendor/meizu/m1822/proprietary/vendor/firmware/focaltech-ofilm-ft8006u-0e-001-m1822.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/focaltech-ofilm-ft8006u-0e-001-m1822.bin \
    vendor/meizu/m1822/proprietary/vendor/firmware/ilitek-tianma-ILI9881-1c-69-m1822.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/ilitek-tianma-ILI9881-1c-69-m1822.bin \
    vendor/meizu/m1822/proprietary/vendor/firmware/leia_pfp_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pfp_470.fw \
    vendor/meizu/m1822/proprietary/vendor/firmware/leia_pm4_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pm4_470.fw \
    vendor/meizu/m1822/proprietary/vendor/firmware/novatek_ts-csot-NT36672A-180919-07-m1822.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts-csot-NT36672A-180919-07-m1822.bin \
    vendor/meizu/m1822/proprietary/vendor/firmware/st21nfc_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/st21nfc_fw.bin \
    vendor/meizu/m1822/proprietary/vendor/firmware/tfa98xx.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/tfa98xx.cnt

PRODUCT_PACKAGES += \
    sensors.ssc \
    audio.primary.msm8953-moto \
    camera.msm8953 \
    lib_motsensorlistener \
    libactuator_dw9763 \
    libactuator_dw9767 \
    libactuator_lc898217xh \
    libadm \
    libcdsprpc \
    libchromatix_mot_ov12a10_common \
    libchromatix_mot_ov12a10_cpp_hfr_120 \
    libchromatix_mot_ov12a10_cpp_hfr_60 \
    libchromatix_mot_ov12a10_cpp_liveshot \
    libchromatix_mot_ov12a10_cpp_preview \
    libchromatix_mot_ov12a10_cpp_snapshot \
    libchromatix_mot_ov12a10_cpp_snapshot_custom \
    libchromatix_mot_ov12a10_cpp_snapshot_downscale \
    libchromatix_mot_ov12a10_cpp_video \
    libchromatix_mot_ov12a10_default_video \
    libchromatix_mot_ov12a10_hfr_120 \
    libchromatix_mot_ov12a10_hfr_120_3a \
    libchromatix_mot_ov12a10_hfr_60 \
    libchromatix_mot_ov12a10_hfr_60_3a \
    libchromatix_mot_ov12a10_postproc \
    libchromatix_mot_ov12a10_preview \
    libchromatix_mot_ov12a10_snapshot \
    libchromatix_mot_ov12a10_zsl_preview_3a \
    libchromatix_mot_ov12a10_zsl_video_3a \
    libchromatix_mot_s5k3l6_common \
    libchromatix_mot_s5k3l6_cpp_hfr_120 \
    libchromatix_mot_s5k3l6_cpp_hfr_60 \
    libchromatix_mot_s5k3l6_cpp_liveshot \
    libchromatix_mot_s5k3l6_cpp_preview \
    libchromatix_mot_s5k3l6_cpp_snapshot \
    libchromatix_mot_s5k3l6_cpp_snapshot_custom \
    libchromatix_mot_s5k3l6_cpp_video_full \
    libchromatix_mot_s5k3l6_hfr_120 \
    libchromatix_mot_s5k3l6_hfr_120_3a \
    libchromatix_mot_s5k3l6_hfr_60 \
    libchromatix_mot_s5k3l6_hfr_60_3a \
    libchromatix_mot_s5k3l6_postproc \
    libchromatix_mot_s5k3l6_snapshot \
    libchromatix_mot_s5k3l6_video_full \
    libchromatix_mot_s5k3l6_zsl_preview_3a \
    libchromatix_mot_s5k3l6_zsl_video_3a \
    libchromatix_mot_s5k4h7_common \
    libchromatix_mot_s5k4h7_cpp_hfr_120 \
    libchromatix_mot_s5k4h7_cpp_liveshot \
    libchromatix_mot_s5k4h7_cpp_preview \
    libchromatix_mot_s5k4h7_cpp_snapshot \
    libchromatix_mot_s5k4h7_cpp_snapshot_custom \
    libchromatix_mot_s5k4h7_cpp_video_full \
    libchromatix_mot_s5k4h7_hfr_120 \
    libchromatix_mot_s5k4h7_hfr_120_3a \
    libchromatix_mot_s5k4h7_postproc \
    libchromatix_mot_s5k4h7_snapshot \
    libchromatix_mot_s5k4h7_video_full \
    libchromatix_mot_s5k4h7_zsl_preview_3a \
    libchromatix_mot_s5k4h7_zsl_video_3a \
    libchromatix_mot_s5k5e9_common \
    libchromatix_mot_s5k5e9_cpp_hfr_120 \
    libchromatix_mot_s5k5e9_cpp_hfr_60 \
    libchromatix_mot_s5k5e9_cpp_liveshot \
    libchromatix_mot_s5k5e9_cpp_preview \
    libchromatix_mot_s5k5e9_cpp_snapshot \
    libchromatix_mot_s5k5e9_cpp_snapshot_custom \
    libchromatix_mot_s5k5e9_cpp_snapshot_downscale \
    libchromatix_mot_s5k5e9_cpp_video_full \
    libchromatix_mot_s5k5e9_hfr_120 \
    libchromatix_mot_s5k5e9_hfr_120_3a \
    libchromatix_mot_s5k5e9_hfr_60 \
    libchromatix_mot_s5k5e9_hfr_60_3a \
    libchromatix_mot_s5k5e9_postproc \
    libchromatix_mot_s5k5e9_snapshot \
    libchromatix_mot_s5k5e9_video_full \
    libchromatix_mot_s5k5e9_zsl_preview_3a \
    libchromatix_mot_s5k5e9_zsl_video_3a \
    libchromatix_ov12a10_m1822_common \
    libchromatix_ov12a10_m1822_cpp_hfr_120 \
    libchromatix_ov12a10_m1822_cpp_hfr_60 \
    libchromatix_ov12a10_m1822_cpp_liveshot \
    libchromatix_ov12a10_m1822_cpp_preview \
    libchromatix_ov12a10_m1822_cpp_snapshot \
    libchromatix_ov12a10_m1822_cpp_snapshot_custom \
    libchromatix_ov12a10_m1822_cpp_snapshot_downscale \
    libchromatix_ov12a10_m1822_cpp_video \
    libchromatix_ov12a10_m1822_default_video \
    libchromatix_ov12a10_m1822_hfr_120 \
    libchromatix_ov12a10_m1822_hfr_120_3a \
    libchromatix_ov12a10_m1822_hfr_60 \
    libchromatix_ov12a10_m1822_hfr_60_3a \
    libchromatix_ov12a10_m1822_postproc \
    libchromatix_ov12a10_m1822_preview \
    libchromatix_ov12a10_m1822_snapshot \
    libchromatix_ov12a10_m1822_zsl_preview_3a \
    libchromatix_ov12a10_m1822_zsl_video_3a \
    libchromatix_s5k4h7_m1822_common \
    libchromatix_s5k4h7_m1822_cpp_hfr_120 \
    libchromatix_s5k4h7_m1822_cpp_liveshot \
    libchromatix_s5k4h7_m1822_cpp_preview \
    libchromatix_s5k4h7_m1822_cpp_snapshot \
    libchromatix_s5k4h7_m1822_cpp_snapshot_custom \
    libchromatix_s5k4h7_m1822_cpp_video_full \
    libchromatix_s5k4h7_m1822_hfr_120 \
    libchromatix_s5k4h7_m1822_hfr_120_3a \
    libchromatix_s5k4h7_m1822_postproc \
    libchromatix_s5k4h7_m1822_snapshot \
    libchromatix_s5k4h7_m1822_video_full \
    libchromatix_s5k4h7_m1822_zsl_preview_3a \
    libchromatix_s5k4h7_m1822_zsl_video_3a \
    libdepthmapwrapper \
    libflash_pmic \
    libgralloc1 \
    libhal_dbg \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    libmm-qcamera \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_frame_algorithm \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_is \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_mct_shimlayer \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_q3a_core \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_algorithm \
    libmmcamera2_stats_lib \
    libmmcamera2_stats_modules \
    libmmcamera_dbg \
    libmmcamera_depth_map \
    libmmcamera_eebinparse \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_facedetection_lib \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_hdr_gb_lib \
    libmmcamera_imglib \
    libmmcamera_imglib_faceproc_adspstub \
    libmmcamera_interface \
    libmmcamera_isp_abf40 \
    libmmcamera_isp_bcc40 \
    libmmcamera_isp_be_stats44 \
    libmmcamera_isp_bf_stats47 \
    libmmcamera_isp_bg_stats44 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_bpc40 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_color_correct40 \
    libmmcamera_isp_color_xform_encoder40 \
    libmmcamera_isp_color_xform_viewfinder40 \
    libmmcamera_isp_cs_stats44 \
    libmmcamera_isp_demosaic40 \
    libmmcamera_isp_demux40 \
    libmmcamera_isp_fovcrop_encoder40 \
    libmmcamera_isp_fovcrop_viewfinder40 \
    libmmcamera_isp_gamma40 \
    libmmcamera_isp_ihist_stats44 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm44 \
    libmmcamera_isp_luma_adaptation40 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff40 \
    libmmcamera_isp_rs_stats44 \
    libmmcamera_isp_scaler_encoder44 \
    libmmcamera_isp_scaler_viewfinder44 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_sub_module \
    libmmcamera_isp_template \
    libmmcamera_isp_wb40 \
    libmmcamera_mot_dw9763_eeprom \
    libmmcamera_mot_dw9767_eeprom \
    libmmcamera_mot_gt24p64b_eeprom \
    libmmcamera_mot_ov12a10 \
    libmmcamera_mot_ov12a10_eeprom \
    libmmcamera_mot_s5k3l6 \
    libmmcamera_mot_s5k5e9 \
    libmmcamera_mot_s5k5e9_eeprom \
    libmmcamera_paaf_lib \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_ppeiscore \
    libmmcamera_quadracfa \
    libmmcamera_s5k4h7 \
    libmmcamera_s5k4h7_eeprom \
    libmmcamera_sat_test_lib \
    libmmcamera_stillmore_lib \
    libmmcamera_sw2d_lib \
    libmmcamera_thread_services \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libmmcamera_tuning \
    libmmcamera_tuning_lookup \
    libmmcamera_vstab_module \
    libmmjpeg \
    libmmjpeg_interface \
    libmmlib2d_interface \
    libmmqjpeg_codec \
    libmmqjpegdma \
    libmot_afd \
    libmot_gpu_mapper \
    libmot_lux_standardization \
    libmotaudioutils \
    libmotimager_utils \
    libqomx_core \
    libqomx_jpegdec \
    libqomx_jpegenc \
    libqomx_jpegenc_pipe \
    libremosaic_daemon \
    libseemore \
    libsensorndkbridge \
    libtinyalsa-moto \
    libtinycompress_vendor \
    libmmieffectswrapper \
    libspeakerbundle \
    com.fingerprints.extension@1.0 \
    MotCamera2 \
    charge_only_mode \
    android.hardware.biometrics.fingerprint@2.1-fpcservice
#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/meizu/m1822

PRODUCT_COPY_FILES += \
    vendor/meizu/m1822/proprietary/product/etc/permissions/com.meizu.moto-uirefresh.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.meizu.moto-uirefresh.xml \
    vendor/meizu/m1822/proprietary/product/etc/permissions/com.meizu.motodisplay.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.meizu.motodisplay.xml \
    vendor/meizu/m1822/proprietary/product/etc/permissions/privapp-permissions-com.meizu.camera2.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/privapp-permissions-com.meizu.camera2.xml \
    vendor/meizu/m1822/proprietary/system_ext/etc/permissions/com.qualcomm.qti.imscmservice-V2.0-java.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.qualcomm.qti.imscmservice-V2.0-java.xml \
    vendor/meizu/m1822/proprietary/system_ext/etc/permissions/com.qualcomm.qti.imscmservice-V2.1-java.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.qualcomm.qti.imscmservice-V2.1-java.xml \
    vendor/meizu/m1822/proprietary/system_ext/etc/permissions/com.qualcomm.qti.imscmservice-V2.2-java.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.qualcomm.qti.imscmservice-V2.2-java.xml \
    vendor/meizu/m1822/proprietary/system_ext/etc/permissions/qcrilhook.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qcrilhook.xml \
    vendor/meizu/m1822/proprietary/system_ext/etc/permissions/telephonyservice.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/telephonyservice.xml \
    vendor/meizu/m1822/proprietary/system_ext/etc/permissions/vendor.qti.hardware.data.connection-V1.0-java.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/vendor.qti.hardware.data.connection-V1.0-java.xml \
    vendor/meizu/m1822/proprietary/system_ext/etc/permissions/vendor.qti.hardware.data.connection-V1.1-java.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/vendor.qti.hardware.data.connection-V1.1-java.xml \
    vendor/meizu/m1822/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile1.xml \
    vendor/meizu/m1822/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile2.xml \
    vendor/meizu/m1822/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile3.xml \
    vendor/meizu/m1822/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile4.xml \
    vendor/meizu/m1822/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile5.xml \
    vendor/meizu/m1822/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile6.xml \
    vendor/meizu/m1822/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile1.xml \
    vendor/meizu/m1822/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile15.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile15.xml \
    vendor/meizu/m1822/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile16.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile16.xml \
    vendor/meizu/m1822/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile17.xml \
    vendor/meizu/m1822/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile18.xml \
    vendor/meizu/m1822/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile19.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile19.xml \
    vendor/meizu/m1822/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile2.xml \
    vendor/meizu/m1822/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile20.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile20.xml \
    vendor/meizu/m1822/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile21.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile21.xml \
    vendor/meizu/m1822/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile3.xml \
    vendor/meizu/m1822/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile32.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile32.xml \
    vendor/meizu/m1822/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile4.xml \
    vendor/meizu/m1822/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile5.xml \
    vendor/meizu/m1822/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile6.xml \
    vendor/meizu/m1822/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile7.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile7.xml \
    vendor/meizu/m1822/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile1.xml \
    vendor/meizu/m1822/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile2.xml \
    vendor/meizu/m1822/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile3.xml \
    vendor/meizu/m1822/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile4.xml \
    vendor/meizu/m1822/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile5.xml \
    vendor/meizu/m1822/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile6.xml \
    vendor/meizu/m1822/proprietary/vendor/etc/data/dsi_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/dsi_config.xml \
    vendor/meizu/m1822/proprietary/vendor/etc/data/netmgr_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/netmgr_config.xml \
    vendor/meizu/m1822/proprietary/vendor/etc/init/android.hardware.bluetooth@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.0-service-qti.rc \
    vendor/meizu/m1822/proprietary/vendor/etc/init/android.hardware.drm@1.2-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.2-service.widevine.rc \
    vendor/meizu/m1822/proprietary/vendor/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc \
    vendor/meizu/m1822/proprietary/vendor/etc/init/android.hardware.keymaster@4.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@4.0-service-qti.rc \
    vendor/meizu/m1822/proprietary/vendor/etc/init/cnd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/cnd.rc \
    vendor/meizu/m1822/proprietary/vendor/etc/init/dataadpl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataadpl.rc \
    vendor/meizu/m1822/proprietary/vendor/etc/init/dataqti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataqti.rc \
    vendor/meizu/m1822/proprietary/vendor/etc/init/ims_rtp_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ims_rtp_daemon.rc \
    vendor/meizu/m1822/proprietary/vendor/etc/init/imsdatadaemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsdatadaemon.rc \
    vendor/meizu/m1822/proprietary/vendor/etc/init/imsqmidaemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsqmidaemon.rc \
    vendor/meizu/m1822/proprietary/vendor/etc/init/imsrcsd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsrcsd.rc \
    vendor/meizu/m1822/proprietary/vendor/etc/init/init.time_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.time_daemon.rc \
    vendor/meizu/m1822/proprietary/vendor/etc/init/netmgrd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/netmgrd.rc \
    vendor/meizu/m1822/proprietary/vendor/etc/init/port-bridge.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/port-bridge.rc \
    vendor/meizu/m1822/proprietary/vendor/etc/init/qcrild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qcrild.rc \
    vendor/meizu/m1822/proprietary/vendor/etc/init/vendor.display.color@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.display.color@1.0-service.rc \
    vendor/meizu/m1822/proprietary/vendor/etc/init/vendor.qti.hardware.perf@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.perf@2.0-service.rc \
    vendor/meizu/m1822/proprietary/vendor/etc/init/vendor.qti.hardware.qteeconnector@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.qteeconnector@1.0-service.rc \
    vendor/meizu/m1822/proprietary/vendor/etc/meizu/mdmctbk/ctbk_cfg.xml:$(TARGET_COPY_OUT_VENDOR)/etc/meizu/mdmctbk/ctbk_cfg.xml \
    vendor/meizu/m1822/proprietary/vendor/etc/perf/commonresourceconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/commonresourceconfigs.xml \
    vendor/meizu/m1822/proprietary/vendor/etc/perf/perfboostsconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perfboostsconfig.xml \
    vendor/meizu/m1822/proprietary/vendor/etc/perf/perfconfigstore.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perfconfigstore.xml \
    vendor/meizu/m1822/proprietary/vendor/etc/perf/targetconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/targetconfig.xml \
    vendor/meizu/m1822/proprietary/vendor/etc/perf/targetresourceconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/targetresourceconfigs.xml \
    vendor/meizu/m1822/proprietary/vendor/etc/permissions/com.meizu.camera2.denali.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.meizu.camera2.denali.xml \
    vendor/meizu/m1822/proprietary/vendor/etc/permissions/com.meizu.motosignature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.meizu.motosignature.xml \
    vendor/meizu/m1822/proprietary/vendor/etc/wifi/WCNSS_qcom_wlan_nv.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/WCNSS_qcom_wlan_nv.bin \
    vendor/meizu/m1822/proprietary/vendor/etc/wifi/WCNSS_qcom_wlan_nv_Argentina.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/WCNSS_qcom_wlan_nv_Argentina.bin \
    vendor/meizu/m1822/proprietary/vendor/etc/wifi/WCNSS_qcom_wlan_nv_Brazil.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/WCNSS_qcom_wlan_nv_Brazil.bin \
    vendor/meizu/m1822/proprietary/vendor/etc/wifi/WCNSS_qcom_wlan_nv_India.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/WCNSS_qcom_wlan_nv_India.bin \
    vendor/meizu/m1822/proprietary/vendor/etc/wifi/WCNSS_qcom_wlan_nv_epa.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/WCNSS_qcom_wlan_nv_epa.bin \
    vendor/meizu/m1822/proprietary/vendor/etc/wifi/WCNSS_wlan_dictionary.dat:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/WCNSS_wlan_dictionary.dat \
    vendor/meizu/m1822/proprietary/vendor/firmware/a530_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_gpmu.fw2 \
    vendor/meizu/m1822/proprietary/vendor/firmware/a530_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pfp.fw \
    vendor/meizu/m1822/proprietary/vendor/firmware/a530_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pm4.fw \
    vendor/meizu/m1822/proprietary/vendor/firmware/a530v1_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v1_pfp.fw \
    vendor/meizu/m1822/proprietary/vendor/firmware/a530v1_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v1_pm4.fw \
    vendor/meizu/m1822/proprietary/vendor/firmware/a530v2_seq.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v2_seq.fw2 \
    vendor/meizu/m1822/proprietary/vendor/firmware/a530v3_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v3_gpmu.fw2 \
    vendor/meizu/m1822/proprietary/vendor/firmware/a530v3_seq.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v3_seq.fw2 \
    vendor/meizu/m1822/proprietary/vendor/firmware/a540_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_gpmu.fw2 \
    vendor/meizu/m1822/proprietary/vendor/radio/qcril_database/qcril.db:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/qcril.db \
    vendor/meizu/m1822/proprietary/vendor/radio/qcril_database/upgrade/0_initial.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/0_initial.sql \
    vendor/meizu/m1822/proprietary/vendor/radio/qcril_database/upgrade/10_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/10_version_qcrildb.sql \
    vendor/meizu/m1822/proprietary/vendor/radio/qcril_database/upgrade/11_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/11_version_qcrildb.sql \
    vendor/meizu/m1822/proprietary/vendor/radio/qcril_database/upgrade/12_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/12_version_qcrildb.sql \
    vendor/meizu/m1822/proprietary/vendor/radio/qcril_database/upgrade/13_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/13_version_qcrildb.sql \
    vendor/meizu/m1822/proprietary/vendor/radio/qcril_database/upgrade/14_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/14_version_qcrildb.sql \
    vendor/meizu/m1822/proprietary/vendor/radio/qcril_database/upgrade/15_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/15_version_qcrildb.sql \
    vendor/meizu/m1822/proprietary/vendor/radio/qcril_database/upgrade/16_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/16_version_qcrildb.sql \
    vendor/meizu/m1822/proprietary/vendor/radio/qcril_database/upgrade/3_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/3_version_qcrildb.sql \
    vendor/meizu/m1822/proprietary/vendor/radio/qcril_database/upgrade/4_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/4_version_qcrildb.sql \
    vendor/meizu/m1822/proprietary/vendor/radio/qcril_database/upgrade/5_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/5_version_qcrildb.sql \
    vendor/meizu/m1822/proprietary/vendor/radio/qcril_database/upgrade/6_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/6_version_qcrildb.sql \
    vendor/meizu/m1822/proprietary/vendor/radio/qcril_database/upgrade/7_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/7_version_qcrildb.sql \
    vendor/meizu/m1822/proprietary/vendor/radio/qcril_database/upgrade/8_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/8_version_qcrildb.sql \
    vendor/meizu/m1822/proprietary/vendor/radio/qcril_database/upgrade/9_version_qcrildb.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/9_version_qcrildb.sql

PRODUCT_PACKAGES += \
    com.qualcomm.qti.imscmservice@1.0_vendor \
    com.qualcomm.qti.imscmservice@2.0_vendor \
    com.qualcomm.qti.imscmservice@2.1_vendor \
    com.qualcomm.qti.imscmservice@2.2_vendor \
    com.qualcomm.qti.uceservice@2.0_vendor \
    com.qualcomm.qti.uceservice@2.1_vendor \
    eglSubDriverAndroid \
    libEGL_adreno \
    libGLESv1_CM_adreno \
    libGLESv2_adreno \
    libQTapGLES \
    libq3dtools_adreno \
    libq3dtools_esx \
    android.hardware.bluetooth@1.0-impl-qti \
    vendor.qti.gnss@3.0-impl \
    vendor.qti.hardware.fm@1.0-impl \
    vendor.qti.hardware.iop@2.0-impl \
    vulkan.msm8953 \
    lib-imsSDP \
    lib-imscmservice \
    lib-imsdpl \
    lib-imsqimf \
    lib-imsrcs-v2 \
    lib-imsrcsbaseimpl \
    lib-imsvtcore \
    lib-imsxml \
    lib-rtpcommon \
    lib-rtpcore \
    lib-rtpsl \
    lib-siputility \
    lib-uceservice \
    libC2D2 \
    libCB \
    libOmxVpp \
    libOpenCL \
    libQSEEComAPI \
    libacdb-fts \
    libacdbloader \
    libacdbrtac \
    libadiertac \
    libadreno_utils \
    libadsp_default_listener \
    libadsprpc \
    libaudcal \
    libaudioalsa \
    libaudioparsers \
    libbtnv \
    libc2d30_bltlib \
    libconfigdb \
    libdataitems \
    libdiag \
    libdsi_netctrl \
    libdsutils \
    libfastcvadsp_stub \
    libfastcvopt \
    libgcs-calwrapper \
    libgcs-ipc \
    libgcs-osal \
    libgcs \
    libgpustats \
    libgsl \
    libhdr_tm \
    libidl \
    libizat_client_api \
    libizat_core \
    liblbs_core \
    libllvm-glnext \
    libllvm-qcom \
    libloc_api_v02 \
    liblocationservice \
    liblocationservice_glue \
    liblowi_client \
    liblqe \
    libmdmdetect \
    libmm-hdcpmgr \
    libmmosal_proprietary \
    libnetmgr \
    libpdmapper \
    libpdnotifier \
    libperfconfig \
    libperfgluelayer \
    libperipheral_client \
    libqcci_legacy \
    libqcmaputils \
    libqdi \
    libqdp \
    libqmi \
    libqmi_cci \
    libqmi_client_helper \
    libqmi_client_qmux \
    libqmi_common_so \
    libqmi_csi \
    libqmi_encdec \
    libqmiservices \
    libqti-iopd-client \
    libqti-perfd-client \
    libqti-perfd \
    libqti-util \
    libqti-utils \
    libqtigef \
    librcc \
    libscalar \
    libscveBlobDescriptor \
    libscveBlobDescriptor_stub \
    libscveCommon \
    libscveCommon_stub \
    libscveObjectSegmentation \
    libscveObjectSegmentation_stub \
    libscveObjectTracker \
    libscveObjectTracker_stub \
    libscvePanorama \
    libscvePanorama_lite \
    libsdedrm \
    libsdm-color \
    libsdm-diag \
    libsdm-disp-vndapis \
    libsdmextension \
    libsdsprpc \
    libsensor1 \
    libsensor_reg \
    libthermalclient \
    libtime_genoff \
    libtinyxml2_1 \
    libvpplibrary \
    libxml \
    libxtadapter \
    libwvdrmengine \
    sensor_calibrate \
    sensors.rp \
    vendor.display.color@1.0 \
    vendor.display.color@1.1 \
    vendor.display.postproc@1.0 \
    vendor.qti.gnss@1.0 \
    vendor.qti.gnss@1.1 \
    vendor.qti.gnss@1.2 \
    vendor.qti.gnss@2.0 \
    vendor.qti.gnss@2.1 \
    vendor.qti.gnss@3.0-service \
    vendor.qti.gnss@3.0 \
    vendor.qti.hardware.fm@1.0_vendor \
    vendor.qti.hardware.iop@1.0_vendor \
    vendor.qti.hardware.iop@2.0_vendor \
    vendor.qti.hardware.radio.am@1.0 \
    vendor.qti.hardware.radio.ims@1.0 \
    vendor.qti.hardware.radio.ims@1.1 \
    vendor.qti.hardware.radio.ims@1.2 \
    vendor.qti.hardware.radio.ims@1.3 \
    vendor.qti.hardware.radio.ims@1.4 \
    vendor.qti.hardware.radio.ims@1.5 \
    vendor.qti.hardware.radio.ims@1.6 \
    vendor.qti.hardware.radio.internal.deviceinfo@1.0 \
    vendor.qti.hardware.radio.lpa@1.0 \
    vendor.qti.hardware.radio.qcrilhook@1.0 \
    vendor.qti.hardware.radio.qtiradio@1.0 \
    vendor.qti.hardware.radio.qtiradio@2.0 \
    vendor.qti.hardware.radio.qtiradio@2.1 \
    vendor.qti.hardware.radio.qtiradio@2.2 \
    vendor.qti.hardware.radio.qtiradio@2.3 \
    vendor.qti.hardware.radio.qtiradio@2.4 \
    vendor.qti.hardware.radio.uim@1.0 \
    vendor.qti.hardware.radio.uim@1.1 \
    vendor.qti.hardware.radio.uim@1.2 \
    vendor.qti.hardware.radio.uim_remote_client@1.0 \
    vendor.qti.hardware.radio.uim_remote_client@1.1 \
    vendor.qti.hardware.radio.uim_remote_client@1.2 \
    vendor.qti.hardware.radio.uim_remote_server@1.0 \
    vendor.qti.hardware.scve.objecttracker@1.0_vendor \
    vendor.qti.hardware.scve.panorama@1.0_vendor \
    vendor.qti.ims.callinfo@1.0_vendor \
    vendor.qti.ims.rcsconfig@1.0_vendor \
    vendor.qti.ims.rcsconfig@1.1_vendor \
    vendor.qti.imsrtpservice@2.0_vendor \
    vendor.qti.imsrtpservice@2.1-service-Impl \
    vendor.qti.imsrtpservice@2.1_vendor \
    vendor.qti.voiceprint@1.0 \
    libcppf \
    libvqzip \
    com.qualcomm.qti.ant@1.0 \
    android.hardware.gatekeeper@1.0-impl-qti \
    vendor.qti.hardware.bluetooth_sar@1.0-impl \
    vendor.qti.hardware.qteeconnector@1.0-impl \
    libGPreqcancel \
    libGPreqcancel_svc \
    libSecureUILib \
    libStDrvInt \
    libadropbox \
    libbt-hidlclient \
    libcacertclient \
    libcne \
    libcneapiclient \
    libcneoplookup \
    libcneqmiutils \
    libcpion \
    libdisp-aba \
    libdrmfs \
    libdrmtime \
    libgarden \
    libgarden_haltests_e2e \
    libgdtap \
    libhdcpsrm \
    libkeymasterdeviceutils \
    libkeymasterprovision \
    libkeymasterutils \
    liblog_vendor \
    liblowi_wifihal \
    libmdmcutback \
    libmotext_inf \
    libnetmgr_common \
    libnetmgr_nr_fusion \
    libnetmgr_rmnet_ext \
    libnlnetmgr \
    libqcrilFramework \
    libqcrildatactl \
    libqdma_file_agent \
    libqisl \
    libqmimotext \
    libqrtr \
    libqsocket \
    libqtikeymaster4 \
    libril-qc-hal-qmi \
    libril-qc-ltedirectdisc \
    libril-qc-radioconfig \
    libril-qcril-hook-oem \
    librilqmiservices \
    librpmb \
    libsecureui_svcsock \
    libsensorndkbridge \
    libsettings \
    libslimclient \
    libssd \
    libsystem_health_mon \
    libwms \
    libwqe \
    libwvhidl \
    qcrild_librilutils \
    qtibus \
    qtimutex \
    vendor.display.color@1.2 \
    vendor.qti.data.factory@2.0 \
    vendor.qti.data.factory@2.1_vendor \
    vendor.qti.data.slm@1.0_vendor \
    vendor.qti.hardware.bluetooth_sar@1.0 \
    vendor.qti.hardware.cacert@1.0 \
    vendor.qti.hardware.data.cne.internal.api@1.0 \
    vendor.qti.hardware.data.cne.internal.constants@1.0 \
    vendor.qti.hardware.data.cne.internal.server@1.0 \
    vendor.qti.hardware.data.connection@1.0 \
    vendor.qti.hardware.data.connection@1.1 \
    vendor.qti.hardware.data.dynamicdds@1.0 \
    vendor.qti.hardware.data.iwlan@1.0 \
    vendor.qti.hardware.data.latency@1.0 \
    vendor.qti.hardware.data.qmi@1.0 \
    vendor.qti.hardware.factory@1.0 \
    vendor.qti.hardware.factory@1.1 \
    vendor.qti.hardware.qteeconnector@1.0 \
    vendor.qti.hardware.tui_comm@1.0 \
    vendor.qti.latency@2.0 \
    libadsp_fd_skel \
    libapps_mem_heap \
    libdspCV_skel \
    libfastcvadsp \
    libfastcvadsp_skel \
    libscveBlobDescriptor_skel \
    libscveObjectSegmentation_skel \
    libscveT2T_skel \
    com.qualcomm.qti.imscmservice@1.0 \
    com.qualcomm.qti.imscmservice@2.0 \
    com.qualcomm.qti.imscmservice@2.1 \
    com.qualcomm.qti.imscmservice@2.2 \
    com.qualcomm.qti.uceservice@2.0 \
    com.qualcomm.qti.uceservice@2.1 \
    fm_helium \
    lib-imscamera \
    lib-imsvideocodec \
    lib-imsvt \
    lib-imsvtextutils \
    lib-imsvtutils \
    libdiag_system \
    libfm-hci \
    libimscamera_jni \
    libimsmedia_jni \
    vendor.qti.hardware.camera.device@1.0 \
    vendor.qti.hardware.fm@1.0 \
    vendor.qti.hardware.iop@1.0 \
    vendor.qti.hardware.iop@2.0 \
    vendor.qti.hardware.scve.objecttracker@1.0-adapter-helper \
    vendor.qti.hardware.scve.objecttracker@1.0 \
    vendor.qti.hardware.scve.panorama@1.0-adapter-helper \
    vendor.qti.hardware.scve.panorama@1.0 \
    vendor.qti.ims.callinfo@1.0 \
    vendor.qti.ims.rcsconfig@1.0 \
    vendor.qti.ims.rcsconfig@1.1 \
    vendor.qti.imsrtpservice@2.0 \
    vendor.qti.imsrtpservice@2.1 \
    MotoSignatureApp \
    CneApp \
    TimeService \
    QtiTelephonyService \
    ims \
    qcrilmsgtunnel \
    com.meizu.motosignature \
    QtiTelephonyServicelibrary \
    com.qualcomm.qti.imscmservice-V2.0-java \
    com.qualcomm.qti.imscmservice-V2.1-java \
    com.qualcomm.qti.imscmservice-V2.2-java \
    com.qualcomm.qti.uceservice-V2.0-java \
    com.qualcomm.qti.uceservice-V2.1-java \
    qcrilhook \
    vendor.qti.data.factory-V1.0-java \
    vendor.qti.data.factory-V2.0-java \
    vendor.qti.data.factory-V2.1-java \
    vendor.qti.data.slm-V1.0-java \
    vendor.qti.hardware.data.connection-V1.0-java \
    vendor.qti.hardware.data.connection-V1.1-java \
    vendor.qti.hardware.data.dynamicdds-V1.0-java \
    vendor.qti.hardware.data.iwlan-V1.0-java \
    vendor.qti.hardware.data.latency-V1.0-java \
    vendor.qti.hardware.factory-V1.0-java \
    vendor.qti.hardware.factory-V1.1-java \
    vendor.qti.ims.callinfo-V1.0-java \
    vendor.qti.ims.rcsconfig-V1.0-java \
    vendor.qti.latency-V2.0-java \
    vendor.qti.gnss@3.0-service.xml \
    adpl \
    adsprpcd \
    capsense_reset \
    cnd \
    cnss-daemon \
    energy-awareness \
    fm_qsoc_patches \
    garden_app \
    hvdcp_opti \
    android.hardware.bluetooth@1.0-service-qti \
    android.hardware.drm@1.2-service.widevine \
    android.hardware.gatekeeper@1.0-service-qti \
    android.hardware.keymaster@4.0-service-qti \
    qcrild \
    vendor.display.color@1.0-service \
    vendor.qti.hardware.perf@2.0-service \
    vendor.qti.hardware.qteeconnector@1.0-service \
    ims_rtp_daemon \
    imsdatadaemon \
    imsqmidaemon \
    imsrcsd \
    ipacm-diag \
    irsc_util \
    loc_launcher \
    lowi-server \
    netmgrd \
    pm-proxy \
    pm-service \
    port-bridge \
    qmi_motext_hook \
    qseecomd \
    qti \
    rmt_storage \
    sensors.qti \
    tftp_server \
    thermal-engine \
    time_daemon \
    xtra-daemon \
    xtwifi-client \
    xtwifi-inet-agent

PRODUCT_PACKAGES += \
    system_ext_priv-app_ims_lib_arm64_libimscamera_jni_so \
    system_ext_priv-app_ims_lib_arm64_libimsmedia_jni_so \
    vendor_firmware_wlan_prima_WCNSS_qcom_wlan_nv_bin \
    vendor_firmware_wlan_prima_WCNSS_qcom_wlan_nv_Argentina_bin \
    vendor_firmware_wlan_prima_WCNSS_qcom_wlan_nv_Brazil_bin \
    vendor_firmware_wlan_prima_WCNSS_qcom_wlan_nv_India_bin \
    vendor_firmware_wlan_prima_WCNSS_qcom_wlan_nv_epa_bin \
    vendor_firmware_wlan_prima_WCNSS_wlan_dictionary_dat \
    vendor_lib_libEGL_adreno_so \
    vendor_lib_libGLESv2_adreno_so \
    vendor_lib64_libEGL_adreno_so \
    vendor_lib64_libGLESv2_adreno_so \
    vendor_lib64_libq3dtools_adreno_so
